;Programa ADDVECT.asm
RESET 			EQU 0H
VETOR 			EQU 60H
				ORG RESET ; PC = 0000H ao se resetar o 8051
				MOV DPTR,#NRO ; endereco nro parcelas a ser somado
				MOV A,#0
				MOVC A,@A+DPTR
				MOV R3,A ; R3 = nro parcelas a ser somado
				MOV DPTR,#DADOS ; end. vetor de dados a ser somado
				MOV R2,#0 ; guarda resultado das somas realizadas
				MOV R0,#0 ; especifica parcela a ser lida do vetor de dados
				MOV R1,#0 ;LIMPA O R1 PARA SER USADO PARA GUARDAR O FLAG CARRY, BIT MAIS SIGNIFICATIVO 
VOLTA:			MOV A,R0
				MOVC A,@A+DPTR ; le parcela
				ADD A,R2
				MOV R2,A ; GUARDA A SOMA EM R2
				
				MOV A,#0 ; LIMPA O ACUMULADOR PARA PODER RECEBER O FLAG CARRY	
				ADDC A,R3  ; ADDC-> SOMA-SE AO CONTEUDO DO ACUMULADOR O CONTEUDO DO FLAG CARRY E O CONTEUDO DO REGISTRADOR ESCOLHIDO 
				MOV P2,#00H ; ATIVA A PORTA P2 COM O BITS MAIS SIGNIFIG PARA FAZER CONTATO COM MEMÓRIA EXTERNA 		
				MOV R1,#00H  ; R1 OU R0, SÃO USADOS PARA FAZER CONTATO COM A MEMÓRIA EXTERNA, NO CASO O R1 RECEBE O BIT MAIS SIGN.
				MOVX @R1,A  ; MOVE O CONTEUDO DO ACUMULADOR PARA A MEMORIA EXTERNA ENDEREÇADA POR P2 E  R1
				
				INC R0
				DJNZ R3,VOLTA
				
				
FIM: 			JMP FIM
				ORG VETOR
NRO: 			DB 15H
DADOS: 			DB 01H,03H,05H,06H,0AH,0E2H,01H,03H,05H,06H,0AH,0E2H,0E2H,0E2H,0E2H	
END
