CS EQU P0.7
END0 EQU P3.3;
END1 EQU P3.4;
					ORG 0h
					CLR END0
					CLR END1
					SETB CS
					
VOLTA:				MOV A,P2
					CPL A ; INVERTE O NIVEL LOGICO -- PORTA P2 VEM COM O NIVEL LOGICO INVERTIDO 
					
					CALL CONVERTE
					
					
					MOV P1,A ; p1 é a porta que vai para o display 7 seg
					
					JMP VOLTA
CONVERTE: 
			INC A ; SE ENCREMENTA O A PARA PARA PC PEGAR O VALOR DA TABELA

			MOVC A,@A+PC
			RET

TABELA: DB 40H, 79H, 24H, 30H, 19H, 12H, 02H, 78H, 00H, 10H, 08H, 03H, 46H,21H, 06H, 0EH
END