;Programa MOSTRA1.asm
CS EQU P0.7
END0 EQU P3.3;
END1 EQU P3.4;
ATRASO EQU 0FEH
CHUCHU EQU 21H ; PARA USAR UMA POSIÇÃO DE MEMÓRIA TEMOS QUE NOMEAR ELA ANTES DE USAR

				ORG 0H
				CLR END0
				CLR END1
				SETB CS
	
VOLTA:		
				MOV R3,#0AH

CONTA:			MOV A,R3
				CALL CONVERTE
				MOV P1,A
				MOV CHUCHU,#ATRASO
				DJNZ R3,CONTA
				
				JMP VOLTA
				
DELAY:			DJNZ CHUCHU,DELAY

				RET
				
CONVERTE:
				MOVC A,@A+PC
				RET				
TABELA: DB 40H, 79H, 24H, 30H, 19H, 12H, 02H, 78H, 00H, 10H, 08H, 03H, 46H,21H, 06H, 0EH
END